Create demo
Edit variable table_name in function prepare_schema or comment/uncomment
lines 90, 95, and 99.

Produces the following error with table_name on line 90:

    ERROR: Migration of schema "public" to version "0 - schema" failed! Changes successfully rolled back.
    ERROR: Migration V0__schema.sql failed
    -------------------------------
    SQL State  : 42601
    Error Code : 0
    Message    : ERROR: syntax error at or near "Type"
      Position: 1
    Location   : /sql/V0__schema.sql (/sql/V0__schema.sql)
    Line       : 35
    Statement  : Type: SEQUENCE

    Caused by: Migration V0__schema.sql failed
    -------------------------------
    SQL State  : 42601
    Error Code : 0
    Message    : ERROR: syntax error at or near "Type"
      Position: 1
    Location   : /sql/V0__schema.sql (/sql/V0__schema.sql)
    Line       : 35
    Statement  : Type: SEQUENCE

    Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "Type"
      Position: 1

Removing SQL comments from the pg_dump (sed on line 124) results in a
different error:

    ERROR: Unable to release PostgreSQL advisory lock
    org.postgresql.util.PSQLException: No results were returned by the query.
            at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:115)
            at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForBoolean(JdbcTemplate.java:558)
            at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.unlock(PostgreSQLAdvisoryLockTemplate.java:490)
            at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:469)
            at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:486)
            at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:528)
            at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:528)
            at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:488)
            at org.flywaydb.core.Flyway$1.execute(Flyway.java:606)
            at org.flywaydb.core.Flyway$1.execute(Flyway.java:557)
            at org.flywaydb.core.Flyway.execute(Flyway.java:973)
            at org.flywaydb.core.Flyway.migrate(Flyway.java:557)
            at org.flywaydb.commandline.Main.executeOperation(Main.java:635)
            at org.flywaydb.commandline.Main.main(Main.java:551)
    ERROR: java.util.NoSuchElementException